[build]
  publish = "public"
  command = "hugo --gc --minify --baseURL $DEPLOY_URL"

[context.deploy-preview]
  command = "hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify --baseURL $DEPLOY_URL"

[context.production]
  command = "hugo --gc --minify --baseURL https://wuwuxuanxuan.com/"
[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.125.4"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "hugo --gc --minify -b $URL"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
